@baseUrl = http://localhost:5080
GET {{baseUrl}}/health
###
GET {{baseUrl}}/api/khoa-hoc?trang=1&kichThuoc=20
###
GET {{baseUrl}}/api/khoa-hoc/1/noi-dung
###
GET {{baseUrl}}/api/lop-hoc?khoaId=1
###
GET {{baseUrl}}/api/loai-khoa-hoc
