import {useEffect,useRef,useState} from 'react';
import {ArrowRight,CalendarDays,Check,Clock3,GraduationCap,MessageSquare,RefreshCw,UserRound} from 'lucide-react';
import type {ArtClass,StudentProfile} from '../types';
import {artCenterService as api,dateTime,vnTime} from '../services/artCenterService';
import type {Attendance,Change,Enrollment,Feedback,Member,Progress} from '../services/artCenterService';

const statusLabels:Record<string,string>={CHO_THANH_TOAN:'Chờ thanh toán',DA_XAC_NHAN:'Đã xác nhận',DA_HUY:'Đã hủy',DA_CHUYEN:'Đã chuyển',HET_HAN:'Hết hạn',CHO_CHUYEN:'Chờ chuyển',CO_MAT:'Có mặt',VANG:'Vắng',CHO_THAM_GIA:'Chưa diễn ra',HUY_BO:'Đã hủy',CHO_XU_LY:'Chờ trung tâm xử lý',DA_TRA_LOI:'Trung tâm đã trả lời',CHO_DUYET:'Chờ duyệt',DA_DUYET:'Đã duyệt',DA_THUC_HIEN:'Đã thực hiện',TU_CHOI:'Không được duyệt',DA_DAT:'Đã xếp lịch bù',DA_HOAN_TAT:'Đã học bù',HOAN_THANH:'Hoàn thành',DE_XUAT:'Chờ duyệt kết quả'};
const label=(status:string)=>statusLabels[status]||status;
const errorText=(error:unknown)=>error instanceof Error?error.message:'Chưa tải được thông tin. Vui lòng thử lại.';
const tabs=[['attendance','Lịch & điểm danh'],['reviews','Nhận xét giáo viên'],['makeup','Học bù'],['schedule','Đổi lịch / lớp'],['feedback','Phản hồi']] as const;
type Tab=typeof tabs[number][0];
function Tag({status}:{status:string}){return <span className={'status learning-status status-'+status.toLowerCase()}>{label(status)}</span>}
function EmptyText({children}:{children:React.ReactNode}){return <p className="learning-empty">{children}</p>}
function FeedbackList({items}:{items:Feedback[]}){return <div className="learning-messages">{items.map(item=><article key={item.id}><div className="learning-row-head"><b>{dateTime(item.guiLuc)}</b><Tag status={item.trangThai}/></div><p>{item.noiDung}</p>{item.traLoi&&<div className="center-reply"><b>Trung tâm phản hồi</b><p>{item.traLoi}</p></div>}</article>)}</div>}

function LearningPanel({enrollment,classes,onEnrollmentChange}:{enrollment:Enrollment;classes:ArtClass[];onEnrollmentChange:()=>void}){
 const [tab,setTab]=useState<Tab>('attendance'),[progress,setProgress]=useState<Progress|null>(null),[feedback,setFeedback]=useState<Feedback[]>([]),[changes,setChanges]=useState<Change[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 const heading=useRef<HTMLHeadingElement>(null),changeKey=useRef({body:'',key:''});
 const [absence,setAbsence]=useState<Attendance|null>(null);
 const active=enrollment.trangThai==='DA_XAC_NHAN'&&enrollment.coTheQuanLy===true;
 useEffect(()=>{let alive=true;setLoading(true);setError('');setProgress(null);setFeedback([]);setChanges([]);Promise.all([api.progress(enrollment.hoSoTheoHocId),api.feedbackHistory(),api.changes()]).then(([p,f,c])=>{if(alive){setProgress(p);setFeedback(f.filter(x=>x.dangKyId===enrollment.id));setChanges(c.filter(x=>x.dangKyNguonId===enrollment.id));}}).catch(e=>{if(alive)setError(errorText(e));}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[enrollment.id,enrollment.hoSoTheoHocId,reload]);
 const records=(progress?.diemDanh||[]).filter(x=>x.trangThai!=='HUY_BO'),future=records.filter(x=>x.trangThai==='CHO_THAM_GIA'&&x.trangThaiBuoi==='DA_XEP_LICH'&&vnTime(x.ngayHoc).getTime()>Date.now()),makeups=progress?.hocBu||[];
 const missed=records.filter(x=>x.trangThai==='VANG'&&x.loaiThamGia==='HOC_CHINH'&&!makeups.some(m=>m.diemDanhVangId===x.id&&m.trangThai!=='DA_HUY'));
 const requests=(kind:Feedback['kind'])=>feedback.filter(x=>x.kind===kind);
 const missedAvailable=missed.filter(x=>!requests('HOC_BU').some(f=>f.diemDanhId===x.id&&f.trangThai==='CHO_XU_LY'));
 const futureAvailable=future.filter(x=>!requests('DOI_LICH').some(f=>f.diemDanhId===x.id&&f.trangThai==='CHO_XU_LY'));
 const targetClasses=classes.filter(c=>Number(c.courseId)===enrollment.khoaHocId&&Number(c.id)!==enrollment.lopHocId&&c.status==='Đang nhận đăng ký');
 const perform=async(action:()=>Promise<unknown>,success:string,form:HTMLFormElement)=>{setBusy(true);setFormError('');setNotice('');try{await action();form.reset();setAbsence(null);setNotice(success);setReload(n=>n+1);onEnrollmentChange();}catch(e){setFormError(errorText(e));}finally{setBusy(false);}};
 const suggestion=(kind:'HOC_BU'|'DOI_LICH')=>async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form);await perform(()=>api.learningRequest(Number(data.get('attendance')),kind,String(data.get('reason')),String(data.get('preferred')||'')),kind==='HOC_BU'?'Đã gửi đề nghị học bù. Trung tâm sẽ phản hồi và xếp lịch phù hợp.':'Đã gửi đề nghị đổi lịch. Lịch hiện tại vẫn áp dụng đến khi trung tâm xác nhận.',form);};
 const change=(type:'HUY'|'CHUYEN')=>async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),reason=String(data.get('reason')),target=Number(data.get('target')),body=JSON.stringify({id:enrollment.id,type,reason,target});if(changeKey.current.body!==body)changeKey.current={body,key:crypto.randomUUID()};await perform(()=>type==='HUY'?api.change(enrollment.id,reason,changeKey.current.key):api.transfer(enrollment.id,target,reason,changeKey.current.key),'Đã gửi yêu cầu. Trung tâm sẽ xem xét theo quy định của khóa.',form);};
 const requestForm=(kind:'HOC_BU'|'DOI_LICH',options:Attendance[])=>active&&options.length?<form className="learning-form" onSubmit={suggestion(kind)}><label className="field"><span>{kind==='HOC_BU'?'Buổi vắng cần học bù':'Buổi muốn đổi lịch'}</span><select name="attendance" required disabled={busy}>{options.map(row=><option key={row.id} value={row.id}>Buổi {row.thuTu||'—'} · {row.chuDe||'Bài thực hành'} · {dateTime(row.ngayHoc)}</option>)}</select></label><label className="field"><span>Khung giờ mong muốn (không bắt buộc)</span><input name="preferred" maxLength={300} placeholder="Ví dụ: chiều Thứ Bảy hoặc sáng Chủ nhật" disabled={busy}/></label><label className="field"><span>Lý do đề nghị</span><textarea name="reason" required maxLength={1000} rows={3} disabled={busy}/></label><button className="btn btn-primary" disabled={busy}>{busy?'Đang gửi…':kind==='HOC_BU'?'Gửi đề nghị học bù':'Gửi đề nghị đổi lịch'} <ArrowRight size={16}/></button></form>:<EmptyText>{!active?(enrollment.coTheQuanLy!==true?'Tài khoản này có quyền xem học tập. Đề nghị học bù/đổi lịch do phụ huynh hoặc người đại diện có quyền đăng ký gửi.':'Cần đăng ký đã xác nhận còn hiệu lực để gửi đề nghị học tập.'):kind==='HOC_BU'?'Chưa có buổi vắng cần đề nghị học bù, hoặc buổi đó đã có đề nghị/lịch bù.':'Chưa có buổi sắp tới để đề nghị đổi lịch, hoặc buổi đó đã có đề nghị chờ xử lý.'}</EmptyText>;

 return <article className="progress-panel learning-workspace" aria-labelledby="learning-title"><div className="learning-heading"><div><span className="kicker">GÓC HỌC TẬP CỦA BẠN</span><h3 id="learning-title" ref={heading} tabIndex={-1}>{enrollment.hocVien} · {enrollment.tenKhoa}</h3><p>{enrollment.tenLop} · {enrollment.lichHoc}</p></div><button type="button" className="learning-refresh" disabled={loading||busy} onClick={()=>{setReload(n=>n+1);onEnrollmentChange()}}><RefreshCw size={16}/> Cập nhật</button></div>
  <div className="learning-tabs" role="tablist" aria-label="Các mục học tập">{tabs.map(([id,title],index)=><button key={id} type="button" id={'learning-tab-'+id} role="tab" aria-selected={tab===id} aria-controls="learning-tabpanel" tabIndex={tab===id?0:-1} onClick={()=>{setTab(id);setAbsence(null);setFormError('')}} onKeyDown={event=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();setTab(tabs[next][0]);setAbsence(null);setFormError('');document.getElementById('learning-tab-'+tabs[next][0])?.focus();}}>{title}</button>)}</div>
  {notice&&<p className="info-note" role="status">{notice}</p>}{formError&&<p className="error-note" role="alert">{formError}</p>}
  <div id="learning-tabpanel" role="tabpanel" aria-labelledby={'learning-tab-'+tab}>
  {loading?<p className="learning-empty" role="status">Đang tải thông tin học tập…</p>:error?<div className="error-note" role="alert"><p>{error}</p><button className="btn btn-soft" onClick={()=>setReload(n=>n+1)}>Thử lại</button></div>:progress&&<>
   {tab==='attendance'&&<><div className="metric-grid"><div><b>{progress.soNoiDungDaThamGia}/{enrollment.soBuoi}</b><span>Nội dung đã tham gia</span></div><div><b>{records.filter(x=>x.trangThai==='VANG').length}</b><span>Buổi vắng</span></div><div><b>{makeups.filter(x=>x.trangThai==='DA_DAT').length}</b><span>Lịch học bù đã xếp</span></div></div><p className="learning-intro">Lịch chính và lịch bù của học viên được cập nhật ở đây. Trạng thái điểm danh do giáo viên hoặc trung tâm ghi nhận.</p><div className="learning-sessions">{records.map(row=><article key={row.id} className="learning-session"><div className="learning-row-head"><b>Buổi {row.thuTu||'—'} · {row.chuDe||'Bài thực hành'}</b><Tag status={row.trangThai}/></div><p><CalendarDays size={16}/>{dateTime(row.ngayHoc)}{row.ketThuc?' – '+vnTime(row.ketThuc).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):''}</p><div className="session-meta">{row.tenPhong&&<span>{row.tenPhong}</span>}<span>{row.loaiThamGia==='HOC_BU'?'Buổi học bù':'Buổi học chính'}</span>{row.baoNghiLuc&&<span>Đã báo nghỉ</span>}</div>{active&&future.some(x=>x.id===row.id)&&!row.baoNghiLuc&&<button className="link-button" onClick={()=>{setAbsence(row);setFormError('')}}>Báo nghỉ buổi này</button>}{absence?.id===row.id&&<form className="learning-form" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;const reason=String(new FormData(form).get('reason'));await perform(()=>api.absence(row.id,reason),'Đã gửi thông báo nghỉ. Trung tâm sẽ ghi nhận theo quy định.',form);}}><label className="field"><span>Lý do báo nghỉ</span><textarea name="reason" rows={2} maxLength={2000} required disabled={busy}/></label><div className="learning-actions"><button className="btn btn-soft" type="button" disabled={busy} onClick={()=>setAbsence(null)}>Đóng</button><button className="btn btn-primary" disabled={busy}>Gửi báo nghỉ</button></div></form>}</article>)}</div>{!records.length&&<EmptyText>Chưa có lịch học hoặc điểm danh cho lượt theo học này.</EmptyText>}</>}
   {tab==='reviews'&&<><p className="learning-intro">Nhận xét, điểm bài thực hành và sản phẩm được ghi theo từng buổi. Lý do báo nghỉ được giữ riêng, không hiển thị như nhận xét của giáo viên.</p><div className="learning-sessions">{records.map(row=><article key={row.id} className="learning-session"><div className="learning-row-head"><b>Buổi {row.thuTu||'—'} · {row.chuDe||'Bài thực hành'}</b><span>{dateTime(row.ngayHoc)}</span></div>{row.ghiLuc?<><p className="teacher-comment">{row.nhanXet||'Giáo viên chưa viết nhận xét cho buổi này.'}</p><div className="session-meta">{row.nguoiNhanXet&&<span>{row.nguoiNhanXet}</span>}<span>{row.diemSanPham!=null?'Điểm sản phẩm: '+row.diemSanPham+'/10':'Chưa có điểm sản phẩm'}</span></div></>:<EmptyText>Chưa có đánh giá của giáo viên cho buổi này.</EmptyText>}{row.sanPhamUrl&&/^https?:\/\//i.test(row.sanPhamUrl)&&<a className="text-link" href={row.sanPhamUrl} target="_blank" rel="noopener noreferrer">Xem bài thực hành <ArrowRight size={16}/></a>}</article>)}</div>{!records.length&&<EmptyText>Nhận xét sẽ xuất hiện khi có buổi học và giáo viên cập nhật.</EmptyText>}{progress.ketQua&&<article className="learning-result"><h4>Kết quả cuối khóa</h4><Tag status={progress.ketQua.ketLuan}/><p>{progress.ketQua.nhanXetTongKet||'Chưa có nhận xét tổng kết.'}</p>{progress.ketQua.diemCuoiKhoaChot!=null&&<b>Điểm cuối khóa: {progress.ketQua.diemCuoiKhoaChot}/10</b>}{progress.ketQua.soXacNhan&&<p>Mã xác nhận: {progress.ketQua.soXacNhan}</p>}</article>}</>}
   {tab==='makeup'&&<><h4>Lịch học bù đã được trung tâm xếp</h4>{makeups.length?<div className="learning-sessions">{makeups.map(row=>{const source=progress.diemDanh.find(x=>x.id===row.diemDanhVangId);return <article className="learning-session" key={row.id}><div className="learning-row-head"><b>{source?`Học bù buổi ${source.thuTu||'—'} · ${source.chuDe||'Bài thực hành'}`:'Buổi học bù'}</b><Tag status={row.trangThai}/></div><p>{row.ngayBu?dateTime(row.ngayBu):'Chưa có giờ học bù'}{row.tenLopBu?' · '+row.tenLopBu:''}</p>{source&&<p>Buổi vắng: {dateTime(source.ngayHoc)}</p>}<small>Hạn hoàn tất: {dateTime(row.hanHoanTat)}</small></article>})}</div>:<EmptyText>Trung tâm chưa xếp lịch học bù cho lượt học này.</EmptyText>}<h4>Đề nghị học bù</h4><p className="learning-intro">Chọn buổi chính đã vắng. Trung tâm kiểm tra thời hạn báo nghỉ, số lượt, nội dung và chỗ trống trước khi xếp lịch bù.</p>{requestForm('HOC_BU',missedAvailable)}<h4>Theo dõi đề nghị học bù</h4>{requests('HOC_BU').length?<FeedbackList items={requests('HOC_BU')}/>:<EmptyText>Bạn chưa gửi đề nghị học bù cho phiếu này.</EmptyText>}</>}
   {tab==='schedule'&&<><h4>Đề nghị đổi lịch một buổi</h4><p className="learning-intro">Gửi khung giờ bạn mong muốn. Trung tâm xem xét giáo viên, phòng và lịch chung của lớp; lịch hiện tại vẫn áp dụng cho đến khi được xác nhận.</p>{requestForm('DOI_LICH',futureAvailable)}{requests('DOI_LICH').length>0&&<FeedbackList items={requests('DOI_LICH')}/>}<h4>Chuyển sang lớp khác cùng khóa</h4>{active&&targetClasses.length?<form className="learning-form" onSubmit={change('CHUYEN')}><label className="field"><span>Lớp mong muốn</span><select name="target" required disabled={busy}>{targetClasses.map(c=><option value={c.id} key={c.id}>{c.title} · {c.schedule}</option>)}</select></label><label className="field"><span>Lý do chuyển lớp</span><textarea name="reason" required maxLength={1000} rows={3} disabled={busy}/></label><button className="btn btn-primary" disabled={busy}>Gửi yêu cầu chuyển lớp</button></form>:<EmptyText>{active?'Chưa có lớp khác cùng khóa đang nhận đăng ký. Bạn có thể gửi đề nghị đổi lịch ở trên để được tư vấn.':'Cần đăng ký đang học đã xác nhận để đề nghị chuyển lớp tại đây.'}</EmptyText>}<div className="learning-messages">{changes.map(c=><article key={c.id}><div className="learning-row-head"><b>{c.loaiYeuCau==='CHUYEN'?'Yêu cầu chuyển lớp':'Yêu cầu hủy lớp'}</b><Tag status={c.trangThai}/></div><p>{c.lyDo}</p><small>{dateTime(c.guiLuc)}</small></article>)}</div></>}
   {tab==='feedback'&&<><h4>Gửi ý kiến về khóa/lớp học</h4><form className="learning-form" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;await perform(()=>api.feedback(enrollment.id,String(new FormData(form).get('content'))),'Đã gửi phản hồi. Bạn có thể theo dõi câu trả lời của trung tâm phía dưới.',form);}}><label className="field"><span>Nội dung phản hồi</span><textarea name="content" required maxLength={2000} rows={4} disabled={busy} placeholder="Chia sẻ trải nghiệm học hoặc nội dung bạn muốn được hỗ trợ."/></label><button className="btn btn-primary" disabled={busy}>Gửi phản hồi <MessageSquare size={16}/></button></form><h4>Phản hồi và câu trả lời của trung tâm</h4>{requests('PHAN_HOI').length?<FeedbackList items={requests('PHAN_HOI')}/>:<EmptyText>Chưa có phản hồi của bạn cho phiếu này.</EmptyText>}{enrollment.coTheQuanLy===true&&['DA_XAC_NHAN','CHO_THANH_TOAN','HET_HAN'].includes(enrollment.trangThai)&&<details className="learning-cancel"><summary>Đề nghị hủy lớp</summary><p>Yêu cầu được trung tâm xem xét theo quy định; việc gửi yêu cầu chưa hủy lớp hoặc hoàn tiền.</p><form className="learning-form" onSubmit={change('HUY')}><label className="field"><span>Lý do đề nghị hủy</span><textarea name="reason" required maxLength={1000} rows={3} disabled={busy}/></label><button className="btn btn-soft" disabled={busy}>Gửi đề nghị hủy lớp</button></form></details>}</>}
  </>}
  </div>
 </article>;
}

export function MemberArea({member,onLogin,onRegister,onChooseStudent,studentFocus,version,classes}:{member:Member|null;onLogin:()=>void;onRegister:(studentId?:string)=>void;onChooseStudent:()=>void;studentFocus:{id:string}|null;version:number;classes:ArtClass[]}){
 const [rows,setRows]=useState<Enrollment[]>([]),[students,setStudents]=useState<StudentProfile[]>([]);
 const [studentId,setStudentId]=useState<string|null>(null),[selectedId,setSelectedId]=useState<number|null>(null);
 const [loadedFor,setLoadedFor]=useState<number|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{
  let alive=true;setError('');setLoading(true);
  if(!member?.thanhVienId){setRows([]);setStudents([]);setLoadedFor(null);setLoading(false);return;}
  Promise.all([api.getStudentProfiles(),api.enrollments()]).then(([profiles,enrollments])=>{
   if(alive){setStudents(profiles);setRows(enrollments);setLoadedFor(member.id);}
  }).catch(e=>{if(alive)setError(errorText(e))}).finally(()=>{if(alive)setLoading(false)});
  return()=>{alive=false};
 },[member?.id,member?.thanhVienId,version,reload]);
 useEffect(()=>{setStudentId(studentFocus?.id??null);setSelectedId(null)},[studentFocus,member?.id]);
 const ready=loadedFor===member?.id,enrollments=ready?rows:[];
 const profiles=ready?students.filter(s=>enrollments.some(row=>row.hocVienId===Number(s.id)&&row.trangThai==='DA_XAC_NHAN')):[];
 const student=profiles.find(s=>s.id===studentId)||profiles[0];
 const visibleRows=student?enrollments.filter(row=>row.hocVienId===Number(student.id)):[];
 const selected=visibleRows.find(row=>row.id===selectedId)||visibleRows.find(row=>row.trangThai==='DA_XAC_NHAN')||visibleRows[0];
 const waiting=enrollments.filter(row=>row.trangThai==='CHO_THANH_TOAN');
 return <section className="section member-area" id="member"><div className="shell">
  <div className="section-head"><div><span className="kicker">GÓC HỌC TẬP</span><h2 id="member-heading" tabIndex={-1}>{student?`Góc học tập của ${student.name}`:'Góc học tập của bạn.'}</h2></div><p>Bấm Học tập trên thanh trên cùng để chọn học viên có lớp đã xác nhận. Mỗi học viên có lịch, điểm danh và nhận xét riêng.</p></div>
  {!member?<div className="member-welcome"><UserRound size={36}/><h3>Hành trình của bạn bắt đầu ở đây.</h3><p>Đăng nhập để xem hồ sơ, phiếu đăng ký và thông tin học tập.</p><button className="btn btn-primary" onClick={onLogin}>Đăng nhập / Đăng ký <ArrowRight size={17}/></button></div>
   :!member.thanhVienId?<EmptyText>Khu học tập này dành cho học viên/người đại diện. Tài khoản nhân viên dùng giao diện quản lý hoặc Swagger theo quyền được cấp.</EmptyText>
   :<>
    {error&&<div className="error-note" role="alert"><p>{error}</p><button className="btn btn-soft" onClick={()=>setReload(n=>n+1)}>Thử lại</button></div>}
    {loading&&!ready?<p className="learning-empty" role="status">Đang tải hồ sơ và các lớp của bạn…</p>
     :!error&&!student?<>
      <div className="learning-welcome"><GraduationCap size={36}/><h3>Chưa có học viên được xác nhận vào lớp.</h3><p>Hồ sơ đã xác minh và phiếu vào lớp đã xác nhận là hai bước riêng. Khi trung tâm xác nhận vào lớp, bạn sẽ chọn được học viên ở mục Học tập để xem lịch, điểm danh và nhận xét.</p><button className="btn btn-primary" onClick={()=>onRegister()}>Đăng ký lớp <ArrowRight size={16}/></button></div>
      {waiting.length>0&&<div className="learning-pending"><h3>Phiếu đang chờ xác nhận học phí</h3><div className="member-grid learning-enrollments">{waiting.map(row=><article key={row.id}><span className="category">{row.maDangKy}</span><h3>{row.hocVien}</h3><p>{row.tenKhoa} · {row.tenLop}</p><Tag status={row.trangThai}/><p>Giữ chỗ đến {dateTime(row.hanGiuCho)}</p></article>)}</div></div>}
     </>:student&&<>
      <div className="family-current-student" data-student-id={student.id}><span className="family-avatar"><UserRound size={24}/></span><div><span className="kicker">HỌC VIÊN ĐANG XEM</span><h3>{student.name}</h3><p>Sinh ngày {new Date(student.birthDate+'T00:00:00+07:00').toLocaleDateString('vi-VN')} · {visibleRows.filter(row=>row.trangThai==='DA_XAC_NHAN').length} lớp đã xác nhận</p></div><button className="btn btn-soft" onClick={onChooseStudent}>Đổi học viên</button></div>
      <div className="family-course-heading"><h3>Khóa / lớp của {student.name}</h3>{student.canRegister===true&&<button className="btn btn-soft" onClick={()=>onRegister(student.id)}>Đăng ký thêm lớp <ArrowRight size={16}/></button>}</div>
      <div className="member-grid learning-enrollments">{visibleRows.map(row=><article key={row.id} className={selected?.id===row.id?'chosen-enrollment':''}><span className="category">{row.maDangKy}</span><h3>{row.tenKhoa}</h3><p><UserRound size={16}/>{row.hocVien}</p><p><CalendarDays size={16}/>{row.tenLop} · {row.lichHoc}</p><Tag status={row.trangThai}/>{row.trangThai==='CHO_THANH_TOAN'&&<p><Clock3 size={16}/>Giữ chỗ đến {dateTime(row.hanGiuCho)}</p>}<button className="course-link" aria-pressed={selected?.id===row.id} onClick={()=>{setSelectedId(row.id);requestAnimationFrame(()=>{const heading=document.getElementById('learning-title');heading?.focus();heading?.scrollIntoView({block:'start'})})}}>Vào lớp & xem học tập {selected?.id===row.id?<Check size={17}/>:<ArrowRight size={17}/>}</button></article>)}</div>
      {selected&&<LearningPanel key={selected.id} enrollment={selected} classes={classes} onEnrollmentChange={()=>setReload(n=>n+1)}/>}</>}
   </>}
 </div></section>;
}
