import {IntroPrograms,Method,Gallery,StudioStory,Questions,Contact} from './components/PublicSections';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,BookOpen,CalendarDays,Check,Clock3,CreditCard,GraduationCap,Menu,Search,ShieldCheck,UserRound,Users,X} from 'lucide-react';
import type {ArtClass,Course,StudentProfile} from './types';
import {artCenterService as api,signedIn,dateTime,clearSession} from './services/artCenterService';
import type {Member} from './services/artCenterService';
import FloatingBotanicals from './animations/FloatingBotanicals';
import {StudentReviews} from './components/StudentReviews';
import {StudentChoices} from './components/StudentChoices';
import {MemberArea} from './components/MemberArea';
import {LearningStudentPicker} from './components/LearningStudentPicker';
import {TeacherCorner} from './components/TeacherCorner';
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'đ';
const message=(e:unknown)=>e instanceof Error?e.message:'Có lỗi. Vui lòng thử lại.';
const age=(date:string,at?:string)=>{const d=new Date(date),n=at?new Date(at+'T00:00:00+07:00'):new Date();return n.getFullYear()-d.getFullYear()-(n.getMonth()<d.getMonth()||n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()?1:0)};
function Logo(){return <a className="logo" href="#top" aria-label="LHL Art — về đầu trang"><img className="brand-logo" src="/logo-lhl-art.jpg" alt="" width="96" height="96"/><span><b>LHL Art</b><small>fine art center</small></span></a>}
function Empty({children}:{children:React.ReactNode}){return <div className="empty-state"><img className="inline-brand empty-brand" src="/logo-lhl-art.jpg" alt=""/><p>{children}</p></div>}
function Dialog({children,onClose,label='Tài khoản và đăng ký học'}:{children:React.ReactNode;onClose:()=>void;label?:string}){const focus=useRef<HTMLDivElement>(null);useEffect(()=>{const prev=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';focus.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=focus.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,a[href],textarea');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===focus.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);prev?.focus()}},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div ref={focus} tabIndex={-1} role="dialog" aria-modal="true" aria-label={label} className="modal wide-modal"><button className="modal-close" aria-label="Đóng" onClick={onClose}><X/></button><div className="modal-head"><Logo/></div>{children}</div></div>}
function AccountForm({onDone}:{onDone:(m:Member)=>void}){const[signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="modal-body" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{const name=String(data.get('name')),pw=String(data.get('password'));if(signup)await api.signup({TenDangNhap:name,MatKhau:pw,HoTen:data.get('fullName'),DienThoai:data.get('phone'),Email:data.get('email')||null});onDone(await api.login(name,pw))}catch(e){setError(message(e))}finally{setBusy(false)}}}><span className="kicker">KHU VỰC THÀNH VIÊN</span><h2>{signup?'Bắt đầu hành trình của bạn.':'Chào mừng bạn trở lại.'}</h2><p>{signup?'Tạo tài khoản để quản lý hồ sơ và đăng ký học.':'Đăng nhập để chọn hồ sơ học viên và xem tiến độ.'}</p>{signup&&<><label className="field"><span>Họ tên người đại diện</span><input name="fullName" required maxLength={150}/></label><label className="field"><span>Số điện thoại</span><input name="phone" type="tel" required maxLength={25}/></label><label className="field"><span>Email (không bắt buộc)</span><input name="email" type="email" maxLength={254}/></label></>}<label className="field"><span>Tên đăng nhập</span><input name="name" autoComplete="username" required minLength={3} maxLength={100}/></label><label className="field"><span>Mật khẩu {signup?'(từ 12 ký tự, có chữ và số)':''}</span><input name="password" type="password" autoComplete={signup?'new-password':'current-password'} required minLength={signup?12:1} maxLength={128}/></label>{error&&<p className="error-note" role="alert">{error}</p>}<button className="btn btn-primary full" disabled={busy}>{busy?'Đang xử lý…':signup?'Tạo tài khoản':'Đăng nhập'} <ArrowRight size={17}/></button><button className="link-button account-switch" type="button" onClick={()=>{setSignup(!signup);setError('')}}>{signup?'Đã có tài khoản? Đăng nhập':'Chưa có tài khoản? Đăng ký'}</button></form>}
function Registration({courses,classes,member,initialClass,initialCourse,initialStudentId,onDone,onClose}:{courses:Course[];classes:ArtClass[];member:Member;initialClass?:ArtClass;initialCourse?:Course;initialStudentId?:string;onDone:()=>void;onClose:()=>void}){
 const[students,setStudents]=useState<StudentProfile[]>([]),[studentId,setStudentId]=useState(initialStudentId||''),[courseId,setCourseId]=useState(initialCourse?.id||initialClass?.courseId||''),[classId,setClassId]=useState(initialClass?.id||''),[step,setStep]=useState(1),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[promo,setPromo]=useState(''),[result,setResult]=useState<Record<string,unknown>|null>(null);
 const retry=useRef({body:'',key:''});
 const load=async()=>{try{setStudents(await api.getStudentProfiles())}catch(e){setError(message(e))}};useEffect(()=>{void load()},[]);
 const student=students.find(s=>s.id===studentId),course=courses.find(c=>c.id===courseId),cl=classes.find(c=>c.id===classId);
 const eligible=student?.canRegister===true&&!!course&&!!cl&&cl.status==='Đang nhận đăng ký'&&age(student.birthDate,cl.startDateISO)>=course.ageMin;
 const submit=async()=>{setBusy(true);setError('');try{const body={HocVienId:Number(studentId),LopHocId:Number(classId),NguoiDangKyId:member.thanhVienId,MaGiamHocPhi:promo.trim()||null};const encoded=JSON.stringify(body);if(retry.current.body!==encoded)retry.current={body:encoded,key:crypto.randomUUID()};const res=await api.submitRegistration({...body,IdempotencyKey:retry.current.key});setResult(res);setStep(4);onDone()}catch(e){setError(message(e))}finally{setBusy(false)}};
 if(!member.thanhVienId)return <div className="modal-body"><h2>Tài khoản nhân viên</h2><p>Trang đăng ký dành cho tài khoản thành viên. Hãy dùng tài khoản người học hoặc người đại diện để đăng ký.</p></div>;
 return <div className="modal-body"><div className="steps">{[1,2,3].map(n=><span key={n} className={step>=n?'done':''}>{n}</span>)}</div>{error&&<p role="alert" className="error-note">{error}</p>}
 {step===1&&<><h2>Ai sẽ cùng mình sáng tạo?</h2><p>Chọn hồ sơ học viên. Hồ sơ mới cần trung tâm xác minh và đánh giá đầu vào trước khi đăng ký lớp.</p><StudentChoices students={students} selectedId={studentId} busy={busy} onSelect={setStudentId} onBusy={setBusy} onError={setError} onDeleted={async id=>{setStudents(current=>current.filter(s=>s.id!==id));if(studentId===id)setStudentId('');await load()}}/>{!students.length&&!adding&&<Empty>Bạn chưa có hồ sơ học viên.</Empty>}<button type="button" className="link-button" disabled={busy} onClick={()=>setAdding(!adding)}>+ Thêm hồ sơ học viên</button>{adding&&<form className="student-profile-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{await api.addStudent({HoTen:d.get('fullName'),NgaySinh:d.get('dob'),QuanHe:d.get('relation'),LienHeKhanCapTen:d.get('emergency'),LienHeKhanCapSDT:d.get('phone'),MucTieuHoc:null});setAdding(false);await load()}catch(e){setError(message(e))}finally{setBusy(false)}}}><div className="form-grid"><label className="field"><span>Họ tên học viên</span><input name="fullName" required maxLength={150}/></label><label className="field"><span>Ngày sinh</span><input name="dob" type="date" required min="1900-01-01" max={new Date().toLocaleDateString('en-CA')}/></label><label className="field"><span>Quan hệ với học viên</span><select name="relation"><option value="CHA">Cha</option><option value="ME">Mẹ</option><option value="GIAM_HO">Giám hộ</option><option value="TU_BAN_THAN">Bản thân</option></select></label><label className="field"><span>Người liên hệ khẩn cấp</span><input name="emergency" required maxLength={150}/></label><label className="field"><span>Số điện thoại khẩn cấp</span><input name="phone" type="tel" required maxLength={25}/></label></div><button className="btn btn-primary full" disabled={busy}>Gửi hồ sơ</button></form>}<div className="modal-actions"><button className="btn btn-primary full" disabled={student?.canRegister!==true||busy} onClick={()=>{setError('');setStep(2)}}>Chọn khóa và lớp <ArrowRight size={17}/></button></div>{student?.verified&&student.canRegister!==true&&<p className="info-note">Tài khoản này có quyền xem học tập. Việc đăng ký lớp do phụ huynh/người đại diện có quyền đăng ký thực hiện.</p>}{student&&!student.verified&&<p className="info-note">Hồ sơ đã được lưu. Trung tâm sẽ xác minh quyền đại diện và đánh giá đầu vào trước khi bạn đăng ký lớp.</p>}</>}
 {step===2&&<><h2>Tìm lớp dành cho {student?.name}.</h2><label className="field"><span>Khóa học</span><select value={courseId} onChange={e=>{setCourseId(e.target.value);setClassId('')}}><option value="">Chọn khóa</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label className="field"><span>Lớp đang tuyển sinh</span><select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Chọn lớp</option>{classes.filter(c=>c.courseId===courseId).map(c=><option value={c.id} key={c.id} disabled={c.status!=='Đang nhận đăng ký'}>{c.title} · {c.schedule} · {c.status}</option>)}</select></label>{course&&<div className="selected-summary"><b>{course.title}</b><span>{course.sessions} buổi × {course.minutesPerSession} phút · {course.level}</span><span>{course.ageMin?`Từ ${course.ageMin} tuổi`:'Không giới hạn tuổi tối thiểu'}</span><span>{course.prerequisites.join(' · ')||'Trung tâm kiểm tra đầu vào khi ghi danh.'}</span></div>}{student&&course&&age(student.birthDate,cl?.startDateISO)<course.ageMin&&<p className="error-note">Học viên chưa đủ tuổi tối thiểu của khóa này.</p>}<p className="info-note">Trung tâm kiểm tra trình độ, lịch học và chỗ trống lần cuối khi lập phiếu.</p><div className="modal-actions"><button className="btn btn-soft" onClick={()=>setStep(1)}>Quay lại</button><button className="btn btn-primary" disabled={!eligible} onClick={()=>setStep(3)}>Xem học phí <ArrowRight size={17}/></button></div></>}
 {step===3&&<><h2>Sẵn sàng cho nét vẽ đầu tiên.</h2><div className="selected-summary"><b>{student?.name} · {cl?.title}</b><span>{cl?.schedule} · Khai giảng {cl?.startDate}</span><span>Đóng đăng ký: {cl?.registrationDeadline}</span></div><div className="price-table"><div><span>Học phí áp dụng của lớp</span><b>{money(cl?.tuitionFee||0)}</b></div><label><span>Mã ưu đãi (nếu có)</span><input value={promo} onChange={e=>setPromo(e.target.value)} maxLength={50}/></label></div><p>Mức giảm hợp lệ và thời hạn giữ chỗ sẽ được xác định trên phiếu. Họa cụ bán riêng được tư vấn tại trung tâm; trang này chưa đặt thêm họa cụ.</p><p className="info-note">Lập phiếu giữ chỗ chưa xác nhận vào lớp. Trung tâm xác nhận sau khi nhận đủ học phí.</p><div className="modal-actions"><button className="btn btn-soft" disabled={busy} onClick={()=>setStep(2)}>Quay lại</button><button className="btn btn-primary" disabled={busy||!eligible} onClick={submit}>{busy?'Đang lập phiếu…':'Xác nhận đăng ký'} <ArrowRight size={17}/></button></div></>}
 {step===4&&result&&<div className="success"><div className="success-icon"><FileCheckIcon/></div><h2>Đã lập phiếu đăng ký.</h2><p>Mã phiếu: <b>{String(result.MaDangKy??result.maDangKy)}</b></p><div className="hold-note"><Clock3/><div><b>Hạn giữ chỗ: {dateTime(String(result.HanGiuCho??result.hanGiuCho))}</b><span>Liên hệ trung tâm để thanh toán; theo dõi trạng thái trong khu vực thành viên.</span></div></div><a href="#member" onClick={onClose} className="btn btn-primary full">Xem khu vực thành viên</a></div>}
 </div>
}
function FileCheckIcon(){return <Check size={34}/>}
export default function App(){const[courses,setCourses]=useState<Course[]>([]),[classes,setClasses]=useState<ArtClass[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[member,setMember]=useState<Member|null>(null),[modal,setModal]=useState<'account'|'register'|'learning'|null>(null),[studentFocus,setStudentFocus]=useState<{id:string}|null>(null),[route,setRoute]=useState(()=>window.location.hash),[pickedCourse,setPickedCourse]=useState<Course>(),[pickedClass,setPickedClass]=useState<ArtClass>(),[pickedStudentId,setPickedStudentId]=useState<string>(),[query,setQuery]=useState(''),[menu,setMenu]=useState(false),[version,setVersion]=useState(0);
 const intent=useRef(false);
 const reload=async()=>{setLoading(true);setError('');try{const[c,l]=await Promise.all([api.getCourses(),api.getClasses()]);setCourses(c);setClasses(l)}catch(e){setError(message(e))}finally{setLoading(false)}};
 useEffect(()=>{void reload();if(signedIn())api.me().then(setMember).catch(()=>{clearSession();setMember(null)});const expire=()=>{setMember(null);setStudentFocus(null);setModal('account')};window.addEventListener('artora:session-expired',expire);return()=>window.removeEventListener('artora:session-expired',expire)},[]);
 const open=(c?:Course,l?:ArtClass,studentId?:string)=>{intent.current=true;setPickedCourse(c);setPickedClass(l);setPickedStudentId(studentId);setModal(member?'register':'account')};
 const goToLearning=()=>{window.location.hash='member';requestAnimationFrame(()=>{const heading=document.getElementById('member-heading');heading?.focus();heading?.scrollIntoView({block:'start'})})};
 useEffect(()=>{const changed=()=>setRoute(window.location.hash);window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed)},[]);
 const openLearningPicker=()=>{setMenu(false);if(!member){intent.current=false;setModal('account')}else if(member.vaiTro==='GIAO_VIEN'){window.location.hash='teacher'}else if(member.thanhVienId){setModal('learning')}else{goToLearning()}};
 const close=()=>setModal(null);
 return <><header className="site-header"><div className="shell nav-wrap"><Logo/><button className="menu-button" aria-label="Mở menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'nav open':'nav'}><a href="#about" onClick={()=>setMenu(false)}>Giới thiệu</a><a href="#programs" onClick={()=>setMenu(false)}>Khóa học</a><a href="#classes" onClick={()=>setMenu(false)}>Lớp học</a><a href="#method" onClick={()=>setMenu(false)}>Phương pháp</a><a href="#gallery" onClick={()=>setMenu(false)}>Góc sáng tạo</a><a href={member?.vaiTro==='GIAO_VIEN'?'#teacher':'#member'} className={member?.thanhVienId||member?.vaiTro==='GIAO_VIEN'?'member-nav-link':undefined} onClick={event=>{setMenu(false);if(member?.thanhVienId){event.preventDefault();openLearningPicker()}}}>{member?.vaiTro==='GIAO_VIEN'?<><BookOpen size={16}/> Góc giáo viên</>:member?.thanhVienId?<><GraduationCap size={16}/> Học tập</>:'Thành viên'}</a>{member?<button className="account-link" onClick={async()=>{try{await api.logout()}catch(e){setError(message(e))}finally{setMember(null);setStudentFocus(null);setModal(null);window.location.hash='top'}}}>Đăng xuất</button>:<button className="account-link" onClick={()=>{intent.current=false;setModal('account')}}>Đăng nhập</button>}<button className="btn btn-primary" onClick={()=>open()}>Đăng ký lớp <ArrowRight size={16}/></button></nav></div></header><FloatingBotanicals/><main>{route==='#teacher'?<TeacherCorner member={member} onLogin={()=>{intent.current=false;setModal('account')}}/>:<>
 <section className="hero compact-hero" id="top"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow"><img className="inline-brand" src="/logo-lhl-art.jpg" alt=""/> MỘT KHÔNG GIAN ĐỂ TỰ DO SÁNG TẠO</span><h1>Chạm vào màu sắc.<br/><em>Đánh thức<br/>chất riêng.</em></h1><p>Không cần vẽ thật giỏi để bắt đầu. Cùng LHL Art khám phá niềm vui sáng tạo, từng nét vẽ và từng buổi học.</p><div className="hero-actions"><a className="btn btn-primary btn-large" href="#programs">Khám phá khóa học <ArrowRight size={19}/></a><button className="text-link" onClick={()=>open()}>Chọn lớp của bạn <ArrowRight size={17}/></button></div><div className="hero-assurances"><span><Users size={17}/> Học trong lớp nhỏ</span><span><BookOpen size={17}/> Lộ trình rõ ràng</span><span><img className="inline-brand" src="/logo-lhl-art.jpg" alt=""/> Tự do thể hiện</span></div></div><div className="hero-visual"><div className="art-frame"><img src="/gallery/ppa-watercolor-study.webp" alt="Ảnh minh họa các bài thực hành màu nước"/><span className="art-caption">MAKE ROOM FOR CREATIVITY.</span></div><div className="studio-note"><span><img className="note-brand" src="/logo-lhl-art.jpg" alt=""/></span><div><b>Một chút màu. Một chút bạn.</b><small>Hành trình sáng tạo bắt đầu từ hôm nay.</small></div></div></div></div></section>
 <StudioStory/><IntroPrograms courses={courses} classes={classes}/><section className="section programs" id="courses"><div className="shell"><div className="section-head"><div><span className="kicker">KHÓA HỌC ĐÃ CÔNG BỐ</span><h2>Một khóa học.<br/>Nhiều điều khám phá.</h2></div><p>Từ những nét vẽ đầu tiên đến ý tưởng của riêng mình. Chọn lộ trình phù hợp và bắt đầu theo cách bạn muốn.</p></div>{error&&<div className="error-note" role="alert"><p>{error}</p><button className="btn btn-soft" onClick={()=>void reload()}>Thử lại</button></div>}{loading?<div className="catalog-loading" aria-live="polite">Đang tìm những lớp học dành cho bạn…</div>:!courses.length&&!error?<Empty>Khóa học mới đang được chuẩn bị. Hãy quay lại khi trung tâm công bố lịch học.</Empty>:<div className="course-grid">{courses.map(c=><article className="course-card" key={c.id}><div className="course-image" style={{background:c.color+'20'}}><img src={c.image} alt=""/><span className="age-pill">{c.ageMin?`Từ ${c.ageMin} tuổi`:'Khám phá mỹ thuật'}</span></div><div className="course-content"><span className="category">{c.category} · {c.level}</span><h3>{c.title}</h3><p>{c.skills.join(' · ')}</p><div className="spec-grid"><span><Clock3 size={14}/>{c.sessions} buổi × {c.minutesPerSession} phút</span><span><CreditCard size={14}/>{money(c.tuitionFee)}</span></div><button className="course-link" onClick={()=>open(c)}>Chọn khóa và xem lớp <ArrowRight size={16}/></button></div></article>)}</div>}</div></section>
 <section className="section class-finder" id="classes"><div className="shell"><div className="finder-panel"><div className="finder-title"><div><span className="kicker light">HẸN BẠN Ở LỚP HỌC</span><h2>Chọn một khung giờ.<br/>Dành riêng cho sáng tạo.</h2></div><p>Xem lịch khai giảng và chỗ còn lại để tìm lớp phù hợp với bạn.</p></div><div className="finder-controls"><label><Search size={18}/><input aria-label="Tìm lớp học" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên khóa, lớp hoặc lịch học"/></label></div><div className="class-list">{classes.filter(c=>(c.title+' '+c.schedule+' '+courses.find(x=>x.id===c.courseId)?.title).toLowerCase().includes(query.toLowerCase())).map(c=><div className="class-row detailed" key={c.id}><div className="class-color" style={{background:courses.find(x=>x.id===c.courseId)?.color}}/><div className="class-main"><small>{c.code} · {courses.find(x=>x.id===c.courseId)?.title}</small><h3>{c.title}</h3><span><CalendarDays size={14}/>{c.schedule}</span></div><div className="class-detail"><small>Khai giảng</small><b>{c.startDate}</b><span>{money(c.tuitionFee||0)}</span></div><div><span className="status">{c.status}</span><small className="seats">Còn {Math.max(0,c.capacity-c.enrolled)}/{c.capacity} chỗ</small></div><button disabled={c.status!=='Đang nhận đăng ký'} onClick={()=>open(undefined,c)}>Chọn lớp <ArrowRight size={16}/></button></div>)}</div>{!classes.length&&<p className="empty">{loading?'Đang tải lịch học…':error?'Chưa tải được lịch học.':'Chưa có lớp được công bố tuyển sinh.'}</p>}</div></div></section>
 <section className="section" id="policy"><div className="shell"><div className="section-head"><div><span className="kicker">AN TÂM TRƯỚC KHI BẮT ĐẦU</span><h2>Rõ ràng từ buổi đầu.</h2></div><p>Bạn luôn biết mình đang đăng ký gì, cần chuẩn bị gì và sẽ học như thế nào.</p></div><div className="policy-grid"><article><UserRound/><h3>Hồ sơ dành riêng cho bạn</h3><p>Một tài khoản quản lý hồ sơ của bạn hoặc các học viên mà bạn đại diện.</p></article><article><Clock3/><h3>Giữ chỗ có thời hạn</h3><p>Hạn giữ chỗ hiển thị trên phiếu đăng ký. Trung tâm xác nhận vào lớp khi nhận đủ học phí.</p></article><article><ShieldCheck/><h3>Thanh toán rõ ràng</h3><p>Mọi khoản thu và hoàn tiền được đối chiếu và ghi nhận theo quy định áp dụng của khóa.</p></article><article><GraduationCap/><h3>Theo dõi từng bước tiến</h3><p>Xem điểm danh, nhận xét và kết quả học tập trong khu vực thành viên.</p></article></div></div></section>
 <Method/><Gallery/><StudentReviews/><Questions/><Contact/><MemberArea member={member} onLogin={()=>{intent.current=false;setModal('account')}} onRegister={studentId=>open(undefined,undefined,studentId)} onChooseStudent={openLearningPicker} studentFocus={studentFocus} version={version} classes={classes}/><section className="cta"><div className="shell cta-inner"><div><span className="kicker light">BẮT ĐẦU TỪ MỘT NÉT VẼ</span><h2>Ý tưởng của bạn<br/>xứng đáng có sắc màu.</h2><p>Tìm khóa học phù hợp và dành một khoảng thời gian cho điều bạn yêu thích.</p></div><button className="btn btn-white btn-large" onClick={()=>open()}>Chọn lớp của bạn <ArrowRight size={18}/></button></div></section></>}</main>
 <footer><div className="shell footer-grid"><div><Logo/><p>Không gian để khám phá mỹ thuật, nuôi dưỡng ý tưởng và tạo nên những điều mang dấu ấn riêng.</p></div><div><b>Khám phá</b><a href="#programs">Khóa học</a><a href="#classes">Lớp học</a><a href="#method">Phương pháp</a><a href="#gallery">Góc sáng tạo</a><a href="#reviews">Cảm nhận học viên</a></div><div><b>Học cùng LHL Art</b><a href="#member">Khu vực thành viên</a><a href="#policy">Thông tin đăng ký</a></div><div><b>Liên hệ</b><span>Thông tin tư vấn và thanh toán được trung tâm cung cấp khi đăng ký.</span></div></div><div className="shell footer-bottom"><span>LHL Art · Creative Studio</span><span>Mỗi nét vẽ, một dấu ấn riêng.</span></div></footer>
 {modal&&<Dialog onClose={close} label={modal==='learning'?'Chọn học viên để xem học tập':undefined}>{modal==='account'?<AccountForm onDone={m=>{setMember(m);setMenu(false);setStudentFocus(null);if(m.vaiTro==='GIAO_VIEN'){setModal(null);window.location.hash='teacher'}else if(intent.current){setModal('register')}else if(m.thanhVienId){setModal('learning')}else{setModal(null);goToLearning()}}}/>:modal==='learning'&&member?<LearningStudentPicker member={member} onSelect={id=>{setStudentFocus({id});setModal(null);goToLearning()}} onRegister={()=>open()}/>:<Registration courses={courses} classes={classes} member={member!} initialCourse={pickedCourse} initialClass={pickedClass} initialStudentId={pickedStudentId} onClose={close} onDone={()=>{setVersion(v=>v+1);void reload()}}/>}</Dialog>}</>
}
